### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dainel40911** [diffFacto/diffFacto#1]
After running instructions about Demo, we can get a npz file.
I would like to know what is the meaning of those files(10_sample 0.npy, anchor.npy).
Moreover, is there any efficient way to show the results?
Thank you very much

**Comment by georgeNakayama** [comment]
Thanks for using our codebase! The naming for the output file is a bit messed up right now. Specifically, **[STEP]_sample 0.npy contains the generated point cloud npy file at diffusion timetep=STEP**. **anchor.npy file contains the shift and scale used for each point to start the diffusion process (please refer to the method section of the paper for details)**. The point cloud can be visualized using any point cloud viewer. Moreover, the segmentation mask for the generated point cloud is under pred_seg_mask.npy. Let me know if you have any other questions!

**Comment by ardianumam** [comment]
Hi @georgeNakayama , thanks for the great work!
I try to visualize the demo output, and here are some inquiries:

1. Inside the npz data, does "input" mean the original shape?  If it does not, which data are the corresponding original shape dan part_id (ground truth)? I try to visualize "input" data with "seg_mask" part label, and it looks weird (see Fig. 1 below)
2. I try to transform "input" using "scale" and "shift" values as `input = input*scale+shift`, the result still looks weird. How can we use the "scale" and "shift" to properly transform "input" (or the generated input) into the final shape? Looks like the shape I show is still in canonical mode? 
3. Which data is the final generated shape and the final part prediction? And how to visualize them properly? E.g., by using the "scale" & "shift" data, since the generated data seem to be still in canonical coordinate

Thanks!

Fig. 1
![image](https://github.com/diffFacto/diffFacto/assets/12822715/97713d36-2b88-4f92-9cdd-b9f4f812934f)

**Comment by georgeNakayama** [comment]
Hi @ardianumam, 

Sorry for the late reply. The demo should generate a npz file containing sampled shape. The "input" shapes are not used for generation. It's there because I didn't clean up the codebase. 

The "scale" and "shift" are the scale and shift used to generate (as conditioning to the cross diffusion network) the shape under "pred". Its generated segmentation can be obtained under "pred_seg_mask". 

"x_sample 0" is the generated shape at diffusion step at x. 

Let me know if you have any further questions.
